vertx:
  uploads-dir: /app/prebid-server/data/file-uploads
http-client:
  circuit-breaker:
    enabled: true
    opening-threshold: 20
    opening-interval-ms: 2000
    closing-interval-ms: 20000
adapters:
  appnexus:
    enabled: true
  conversant:
    enabled: true
  pubmatic:
    enabled: true
  pulsepoint:
    enabled: true
  rubicon:
    enabled: true
    pbs-enforces-gdpr: false
  sovrn:
    enabled: true
auction:
  ad-server-currency: USD
metrics:
  graphite:
    host: graphite
    port: 3003
    interval: 60
  accounts:
    default-verbosity: detailed
analytics:
  rp:
    enabled: true
    pbs-version: 0.0.1
    sampling-factor:
      account:
        15946: 1
cache:
  scheme: https
  path: /cache
  query: uuid=%PBS_CACHE_UUID%
  banner-ttl-seconds: 300
  video-ttl-seconds: 300
settings:
  database:
    type: mysql
    stored-requests-query: SELECT uuid, config, 'request' as dataType FROM stored_requests WHERE uuid IN (%REQUEST_ID_LIST%) UNION ALL SELECT uuid, config, 'imp' as dataType FROM stored_requests WHERE uuid IN (%IMP_ID_LIST%)
    amp-stored-requests-query: SELECT uuid, config, 'request' as dataType FROM stored_requests WHERE uuid IN (%REQUEST_ID_LIST%)
    circuit-breaker:
      enabled: true
      opening-threshold: 10
      opening-interval-ms: 2000
      closing-interval-ms: 20000
recaptcha-url: https://www.google.com/recaptcha/api/siteverify
recaptcha-secret: secret_value
host-cookie:
  opt-out-url: http://prebid.org/optout
  opt-in-url: http://prebid.org/optin
  domain: rubiconproject.com
  family: rubicon
  cookie-name: khaos
  optout-cookie:
    name: trp_optout
    value: "true"
status-response: ready
gdpr:
  host-vendor-id: 52
  vendorlist:
    filesystem-cache-dir: /app/prebid-server/data/vendorlist-cache
  geolocation:
    enabled: true
  rubicon:
    enable-cookie: true
    rsid-cookie-encryption-key: fdvndnvavad jdavao89571-34242134fdfads
