vertx:
  http-server-instances: ${vertx.verticle.instances}
  uploads-dir: /app/prebid-server/data/file-uploads
adapters:
  appnexus:
    enabled: true
    pbs-enforces-gdpr: false
  conversant:
    enabled: true
    pbs-enforces-gdpr: false
  rubicon:
    enabled: true
    pbs-enforces-gdpr: false
  pubmatic:
    enabled: true
    pbs-enforces-gdpr: false
  pulsepoint:
    enabled: true
    pbs-enforces-gdpr: false
  adform:
    pbs-enforces-gdpr: false
  adtelligent:
    pbs-enforces-gdpr: false
  eplanning:
    pbs-enforces-gdpr: false
  facebook:
    pbs-enforces-gdpr: false
  indexexchange:
    pbs-enforces-gdpr: false
  lifestreet:
    pbs-enforces-gdpr: false
  openx:
    pbs-enforces-gdpr: false
  sovrn:
    pbs-enforces-gdpr: false
auction:
  ad-server-currency: USD
metrics:
  graphite:
    host: graphite
    port: 3003
    interval: 60
cache:
  scheme: https
  query: uuid=%PBS_CACHE_UUID%
settings:
  database:
    type: mysql
    stored-requests-query: SELECT uuid, config, 'request' as dataType FROM stored_requests WHERE uuid IN (%REQUEST_ID_LIST%) UNION ALL SELECT uuid, config, 'imp' as dataType FROM stored_requests WHERE uuid IN (%IMP_ID_LIST%)
    amp-stored-requests-query: SELECT uuid, config, 'request' as dataType FROM stored_requests WHERE uuid IN (%REQUEST_ID_LIST%)
recaptcha-url: https://www.google.com/recaptcha/api/siteverify
recaptcha-secret: secret_value
host-cookie:
  opt-out-url: http://prebid.org/optout
  opt-in-url: http://prebid.org/optin
  domain: rubiconproject.com
  family: rubicon
  cookie-name: khaos
  optout-cookie:
    name: trp_optout
    value: "true"
status-response: ready
gdpr:
  vendorlist:
    filesystem-cache-dir: /app/prebid-server/data/vendorlist-cache
  rubicon:
    enable-cookie: false

