vertx:
  uploads-dir: /app/prebid-server/data/file-uploads
admin-endpoints:
  version:
    enabled: true
    on-application-port: true
    protected: false
  currency-rates:
    enabled: true
    on-application-port: true
  storedrequest:
    enabled: true
    on-application-port: true
  storedrequest-amp:
    enabled: true
    on-application-port: true
  cache-invalidation:
    enabled: true
    on-application-port: true
  logging-httpinteraction:
    enabled: true
    on-application-port: true
  logging-changelevel:
    enabled: true
    on-application-port: true
  tracelog:
    enabled: true
    on-application-port: true
http-client:
  circuit-breaker:
    enabled: true
    opening-threshold: 100
    opening-interval-ms: 2000
    closing-interval-ms: 20000
adapters:
  adform:
    enabled: true
  adgeneration:
    enabled: true
  adhese:
    enabled: true
  adot:
    enabled: true
  appnexus:
    enabled: true
    aliases:
      districtm:
        enabled: true
  bidmachine:
    enabled: true
  brightroll:
    enabled: true
  consumable:
    enabled: true
  conversant:
    enabled: true
  datablocks:
    enabled: true
    usersync:
      url: https://s.0cf.io/sync?gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}&r=
      type: iframe
  deepintent:
    enabled: true
  emxdigital:
    enabled: true
  engagebdr:
    enabled: true
  grid:
    enabled: true
    aliases:
      trustx:
        enabled: true
        endpoint: https://grid.bidswitch.net/sp_bid?sp=trustx
        usersync:
          redirect-url: /setuid?bidder=trustx&gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}&uid=${BSW_UUID}?gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}
          cookie-family-name: trustx
  gumgum:
    enabled: true
  improvedigital:
    enabled: true
  inmobi:
    enabled: true
    usersync:
      url: https://id5-sync.com/i/495/0.gif?gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}&callback=
      redirect-url: /setuid?bidder=inmobi&gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}&uid={ID5UID}
  ix:
    enabled: true
    endpoint: http://rubicon-us-east.lb.indexww.com/pbs?p=189517
    usersync:
      url: https://ssum.casalemedia.com/usermatchredir?s=189517&gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}&cb=
      redirect-url: /setuid?bidder=ix&gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}&uid=
  logicad:
    enabled: true
  marsmedia:
    enabled: true
  nobid:
    enabled: true
  openx:
    enabled: true
  outbrain:
    enabled: true
    endpoint: http://b1h.zemanta.com/api/bidder/prebid/bid/
    usersync:
      url: https://b1h.zemanta.com/usersync/prebid?gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}&cb=
  pubmatic:
    enabled: true
  pubnative:
    enabled: true
  pulsepoint:
    enabled: true
  rtbhouse:
    enabled: true
  rubicon:
    enabled: true
  smaato:
    enabled: true
  smartadserver:
    enabled: true
  smartyads:
    enabled: true
  sovrn:
    enabled: true
  synacormedia:
    enabled: true
  tappx:
    enabled: true
  triplelift:
    enabled: true
    endpoint: https://tlx.3lift.com/s2s/auction?sra=1&supplier_id=39
  ttx:
    enabled: true
    aliases:
      '33across':
        enabled: true
  verizonmedia:
    enabled: true
  vrtcal:
    enabled: true
  yieldlab:
    enabled: true
  yieldmo:
    enabled: true
  yieldone:
    enabled: true
auction:
  ad-server-currency: USD
  enforce-random-bid-id: true
  validations:
    banner-creative-max-size: skip
    secure-markup: skip
metrics:
  graphite:
    enabled: true
    host: graphite
    port: 3003
    interval: 60
  accounts:
    default-verbosity: none
    basic-verbosity: 12272, 12154, 10306, 12954, 9619
    detailed-verbosity: 9262, 9852, 12562
analytics:
  rp:
    enabled: true
    host-vendor-id: 52
    log:
      empty-dimensions: true
cache:
  scheme: https
  path: /cache
  query: uuid=
  banner-ttl-seconds: 300
  video-ttl-seconds: 900
settings:
  generate-storedrequest-bidrequest-id: true
  enforce-valid-account: true
  database:
    type: mysql
    account-query: >
      SELECT
        uuid,
        JSON_MERGE_PATCH(config, JSON_OBJECT(
          'status', status,
          'auction', JSON_OBJECT(
            'price-granularity', price_granularity,
            'banner-cache-ttl', banner_cache_ttl,
            'video-cache-ttl', video_cache_ttl,
            'truncate-target-attr', truncate_target_attr,
            'default-integration', default_integration,
            'bid-validations', bid_validations,
            'events', JSON_OBJECT(
              'enabled', NOT NOT(events_enabled)
            )
          ),
          'privacy', JSON_OBJECT(
            'enforce-ccpa', NOT NOT(enforce_ccpa),
            'gdpr', tcf_config
          ),
          'analytics', JSON_MERGE_PATCH(analytics_config, JSON_OBJECT(
            'modules', JSON_OBJECT(
              'rubicon', JSON_OBJECT(
                'sampling-factor', analytics_sampling_factor
              )
            )
          ))
        )) as consolidated_config
        FROM accounts_account
        WHERE uuid = %ACCOUNT_ID%
        LIMIT 1
    stored-requests-query: SELECT accountId, uuid, config, 'request' as dataType FROM stored_requests WHERE uuid IN (%REQUEST_ID_LIST%) UNION ALL SELECT accountId, uuid, config, 'imp' as dataType FROM stored_requests WHERE uuid IN (%IMP_ID_LIST%)
    amp-stored-requests-query: SELECT accountId, uuid, config, 'request' as dataType FROM stored_requests WHERE uuid IN (%REQUEST_ID_LIST%)
    stored-responses-query: SELECT resid, responseData FROM stored_responses WHERE resid IN (%RESPONSE_ID_LIST%)
    circuit-breaker:
      enabled: true
      opening-threshold: 100
      opening-interval-ms: 2000
      closing-interval-ms: 20000
  in-memory-cache:
    notification-endpoints-enabled: true
recaptcha-url: https://www.google.com/recaptcha/api/siteverify
recaptcha-secret: secret_value
host-cookie:
  opt-out-url: http://prebid.org/optout
  opt-in-url: http://prebid.org/optin
  domain: rubiconproject.com
  family: rubicon
  cookie-name: khaos
  optout-cookie:
    name: trp_optout
    value: "true"
status-response: ready
gdpr:
  default-value: 1
  host-vendor-id: 52
  vendorlist:
    v1:
      cache-dir: /app/prebid-server/data/vendorlist-cache
      fallback-vendor-list-path: /app/prebid-server/conf/tcf-v1-fallback-vendorlist.json
      deprecated: true
    v2:
      cache-dir: /app/prebid-server/data/vendorlist2-cache
  purposes:
    p2:
      enforce-purpose: full
    p7:
      enforce-purpose: "no"
  consent-string-means-in-scope: true
  rubicon:
    enable-cookie: true
geolocation:
  enabled: true
  type: netacuity
  circuit-breaker:
    enabled: true
    opening-threshold: 100
    opening-interval-ms: 2000
    closing-interval-ms: 20000
