vertx:
  uploads-dir: /app/prebid-server/data/file-uploads
adapters:
  appnexus:
    enabled: true
  conversant:
    enabled: true
  rubicon:
    enabled: true
  pubmatic:
    enabled: true
  pulsepoint:
    enabled: true
auction:
  ad-server-currency: USD
metrics:
  graphite:
    host: graphite
    port: 3003
    interval: 60
  accounts:
    default-verbosity: detailed
cache:
  scheme: https
  query: uuid=%PBS_CACHE_UUID%
settings:
  database:
    type: mysql
    stored-requests-query: SELECT uuid, config, 'request' as dataType FROM stored_requests WHERE uuid IN (%REQUEST_ID_LIST%) UNION ALL SELECT uuid, config, 'imp' as dataType FROM stored_requests WHERE uuid IN (%IMP_ID_LIST%)
    amp-stored-requests-query: SELECT uuid, config, 'request' as dataType FROM stored_requests WHERE uuid IN (%REQUEST_ID_LIST%)
recaptcha-url: https://www.google.com/recaptcha/api/siteverify
recaptcha-secret: secret_value
host-cookie:
  opt-out-url: http://prebid.org/optout
  opt-in-url: http://prebid.org/optin
  domain: rubiconproject.com
  family: rubicon
  cookie-name: khaos
  optout-cookie:
    name: trp_optout
    value: "true"
status-response: ready
gdpr:
  vendorlist:
    filesystem-cache-dir: /app/prebid-server/data/vendorlist-cache
  rubicon:
    enable-cookie: true
    rsid-cookie-encryption-key: fdvndnvavad jdavao89571-34242134fdfads
